### ISSUE TITLE
Kudos can't find slack account

### ISSUE THREAD

**Issue by moteleolu** [Factual/kudos#52] opened 2018-08-21 23:10 UTC
# 🐛 Bug Report

Got this shortly after receiving kudos email notification
<img width="1040" alt="screen shot 2018-08-21 at 4 02 19 pm" src="https://user-images.githubusercontent.com/8581299/44433763-86af2680-a55c-11e8-878e-3f6b3ada8a26.png">

However: I have an account
<img width="495" alt="screen shot 2018-08-21 at 4 04 20 pm" src="https://user-images.githubusercontent.com/8581299/44433800-af372080-a55c-11e8-85ea-c81cf7f1ec7e.png">

**Comment by joecox** [comment] 2018-08-24 17:13
Thanks for reporting @moteleolu!  We're not 100% of the issue yet, so we're basically just disabling this email for now.

I will close this issue as a duplicate of #50, you can follow along there for a full fix if you're interested.

**Closed by joecox** 2018-08-24 17:13 UTC
